apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spcg-sniffer
  namespace: {{ .Values.namespaces.capture }}
spec:
  selector:
    matchLabels:
      app: spcg-sniffer
  template:
    metadata:
      labels:
        app: spcg-sniffer
    spec:
      serviceAccountName: pcap-executor
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: netobserv-ebpf-agent
          image: {{ .Values.capture.sniffer.image }}
          ports:
            - containerPort: 2055
              name: grpc
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: spcg-sniffer
  namespace: {{ .Values.namespaces.capture }}
spec:
  clusterIP: None
  selector:
    app: spcg-sniffer
  ports:
    - port: 2055
      targetPort: 2055
