apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.capture }}
  labels:
    spcg.io/tier: capture
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    spcg.io/tier: frontend
    pod-security.kubernetes.io/enforce: restricted
