apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-capture.yaml
  - namespace-frontend.yaml
  - network-policies.yaml
  - config-capture-admission.yaml
  - deployment-capture.yaml
  - deployment-frontend.yaml
  - deployment-neo4j.yaml
