/** Cytoscape stylesheet from networkplot html.py */
export const CYTOSCAPE_STYLES = [
  {
    selector: 'node[type = "layer"]',
    style: { display: "none", width: 1, height: 1, opacity: 0 },
  },
  {
    selector: "node",
    style: {
      shape: "ellipse",
      width: 30,
      height: 30,
      padding: "0px",
      "background-color": "#111827",
      "border-width": 1.5,
      "border-color": "data(border)",
      label: "data(label)",
      "text-wrap": "ellipsis",
      "text-max-width": 140,
      "font-size": 10,
      "font-weight": 500,
      "text-valign": "bottom",
      "text-halign": "center",
      color: "#dbe3f1",
      "background-image": "data(iconUrl)",
      "background-fit": "none",
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "50%",
      "background-position-y": "50%",
      "background-repeat": "no-repeat",
      "text-margin-y": 16,
      "text-outline-width": 0,
    },
  },
  {
    selector: 'node[type = "pod"]',
    style: {
      width: 36,
      height: 36,
      "font-size": 10,
      "text-max-width": 160,
      "background-width": "20px",
      "background-height": "20px",
      "border-width": 2.5,
    },
  },
  {
    selector: 'node[directPod = "true"]',
    style: { "border-width": 4 },
  },
  {
    selector: 'node[namespaceOnly = "true"]',
    style: { "border-style": "dashed", "font-weight": 500, opacity: 0.88 },
  },
  {
    selector: "node:selected",
    style: { "border-width": 4 },
  },
  {
    selector: "edge",
    style: {
      width: "data(edgeWidth)",
      "target-arrow-shape": "triangle",
      "curve-style": "unbundled-bezier",
      "control-point-distances": "data(curveShift)",
      "control-point-weights": 0.45,
      label: "data(label)",
      "font-size": 8,
      "font-weight": 600,
      "text-rotation": "autorotate",
      color: "#dbe8ff",
      "text-background-color": "#020617",
      "text-background-opacity": 0.7,
      "text-background-padding": 2,
      "line-color": "#5eead4",
      "target-arrow-color": "#5eead4",
      "line-cap": "round",
      "arrow-scale": 0.55,
      "line-dash-pattern": [12, 8],
      "line-dash-offset": 0,
      opacity: 0.9,
    },
  },
  {
    selector: 'edge[edgeType = "direct"]',
    style: {
      "line-color": "#34d399",
      "target-arrow-color": "#34d399",
      width: 2.8,
      color: "#86efac",
    },
  },
  {
    selector: 'edge[edgeType = "https"]',
    style: { "line-color": "#0d6efd", "target-arrow-color": "#0d6efd" },
  },
  {
    selector: 'edge[edgeType = "snat"]',
    style: {
      "line-color": "#fb7185",
      "target-arrow-color": "#fb7185",
      "line-style": "dashed",
    },
  },
  {
    selector: 'edge[edgeType = "scheduled"]',
    style: { "line-color": "#f59e0b", "target-arrow-color": "#f59e0b" },
  },
  {
    selector: 'edge[edgeType = "egressservice"]',
    style: {
      "line-color": "#7c3aed",
      "target-arrow-color": "#7c3aed",
      "line-style": "dashed",
    },
  },
  {
    selector: ".hl-edge",
    style: { width: 4.2, "z-index": 9, opacity: 1 },
  },
  {
    selector: ".faded",
    style: { opacity: 0.18 },
  },
];
