apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spcg-neo4j-data
  namespace: pcap-frontend
  labels:
    app: spcg-neo4j
    spcg.io/tier: graph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
