apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spcg-ui-portal-route-reader
  namespace: pcap-frontend
$patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spcg-ui-portal-route-reader
  namespace: pcap-frontend
$patch: delete