apiVersion: v1
kind: Namespace
metadata:
  name: random-scanner
  labels:
    purpose: spcg-lab-threat-sim
    app.kubernetes.io/part-of: spcg-lab
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
