namespaces:
  capture: pcap-capture
  frontend: pcap-frontend

capture:
  backend:
    image: spcg-backend-engine:latest
    replicas: 1
  agentImage: quay.io/netobserv/netobserv-ebpf-agent:release-1.8

frontend:
  uiPortal:
    image: spcg-ui-portal:latest
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
  web:
    image: spcg-frontend:latest
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi

mtls:
  enabled: true
  secretName: spcg-engine-mtls
