apiVersion: v1
kind: Namespace
metadata:
  name: spcg-control
  labels:
    app.kubernetes.io/part-of: spcg
    spcg.io/role: control
    spcg.io/tier: control
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
