apiVersion: v1
kind: Service
metadata:
  name: spcg-frontend
  namespace: pcap-frontend
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app: spcg-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
