// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: capture/v1/capture.proto

package capturev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaptureService_StreamPackets_FullMethodName = "/capture.v1.CaptureService/StreamPackets"
)

// CaptureServiceClient is the client API for CaptureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptureService streams raw packet bytes from privileged netobserv workers.
type CaptureServiceClient interface {
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TargetPodRequest, CaptureChunk], error)
}

type captureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureServiceClient(cc grpc.ClientConnInterface) CaptureServiceClient {
	return &captureServiceClient{cc}
}

func (c *captureServiceClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TargetPodRequest, CaptureChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CaptureService_ServiceDesc.Streams[0], CaptureService_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TargetPodRequest, CaptureChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_StreamPacketsClient = grpc.BidiStreamingClient[TargetPodRequest, CaptureChunk]

// CaptureServiceServer is the server API for CaptureService service.
// All implementations must embed UnimplementedCaptureServiceServer
// for forward compatibility.
//
// CaptureService streams raw packet bytes from privileged netobserv workers.
type CaptureServiceServer interface {
	StreamPackets(grpc.BidiStreamingServer[TargetPodRequest, CaptureChunk]) error
	mustEmbedUnimplementedCaptureServiceServer()
}

// UnimplementedCaptureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureServiceServer struct{}

func (UnimplementedCaptureServiceServer) StreamPackets(grpc.BidiStreamingServer[TargetPodRequest, CaptureChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedCaptureServiceServer) mustEmbedUnimplementedCaptureServiceServer() {}
func (UnimplementedCaptureServiceServer) testEmbeddedByValue()                        {}

// UnsafeCaptureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureServiceServer will
// result in compilation errors.
type UnsafeCaptureServiceServer interface {
	mustEmbedUnimplementedCaptureServiceServer()
}

func RegisterCaptureServiceServer(s grpc.ServiceRegistrar, srv CaptureServiceServer) {
	// If the following call pancis, it indicates UnimplementedCaptureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptureService_ServiceDesc, srv)
}

func _CaptureService_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CaptureServiceServer).StreamPackets(&grpc.GenericServerStream[TargetPodRequest, CaptureChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_StreamPacketsServer = grpc.BidiStreamingServer[TargetPodRequest, CaptureChunk]

// CaptureService_ServiceDesc is the grpc.ServiceDesc for CaptureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capture.v1.CaptureService",
	HandlerType: (*CaptureServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _CaptureService_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "capture/v1/capture.proto",
}
