apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.DAEMONSET_NAME}}
  namespace: {{.CAPTURE_NAMESPACE}}
  labels:
    app: spcg-sensor
    spcg.io/session: "{{.SESSION_ID}}"
spec:
  selector:
    matchLabels:
      app: spcg-sensor
      spcg.io/session: "{{.SESSION_ID}}"
  template:
    metadata:
      labels:
        app: spcg-sensor
        spcg.io/session: "{{.SESSION_ID}}"
        spcg.io/build: "{{.BUILD_ID}}"
    spec:
      serviceAccountName: pcap-executor
      automountServiceAccountToken: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
      containers:
        - name: netobserv-ebpf-agent
          image: "{{.AGENT_IMAGE}}"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: CACHE_ACTIVE_TIMEOUT
              value: "1s"
            - name: ENABLE_PCA
              value: "true"
            - name: METRICS_ENABLE
              value: "false"
            - name: LOG_LEVEL
              value: info
            - name: FLOW_FILTER_RULES
              value: '{{.FLOW_FILTER_RULES}}'
            - name: TC_ATTACH_MODE
              value: "any"
            - name: DIRECTION
              value: "both"
            - name: EXPORT
              value: "grpc"
            - name: TARGET_HOST
              value: "{{.COLLECTOR_HOST}}"
            - name: TARGET_PORT
              value: "{{.COLLECTOR_PORT}}"
          volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: HostToContainer
            - name: host-netns
              mountPath: /var/run/netns
              mountPropagation: HostToContainer
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: host-netns
          hostPath:
            path: /var/run/netns
            type: DirectoryOrCreate
