apiVersion: apps/v1
kind: Deployment
metadata:
  name: spcg-ui-portal
  namespace: pcap-frontend
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spcg-frontend
  namespace: pcap-frontend
spec:
  replicas: 2
